### PR TITLE
Better dist detection, add blackPanther support

### PR DESCRIPTION
**Pull request by blackPantherOS**
If useful for you...
Added working Fedora installer
Added working blackPanther OS installer
Better and clean dist detection
Cosmetics
Have a nice weekend.

### CODE REVIEW

**Comment by LethalEthan** [comment]
Thanks, been away for a week this is the best thing which has happened :laughing:

**Comment by LethalEthan** [comment]
Just did a bit of testing it seems the l2ping doesn't work the first time :confused:

**Comment by blackPantherOS** [comment]
Hi Mate, I applied few modification on original python script, because blackPanther OS does not use sudo. I checked your script, and working as user after I use setcap. Look into my fork. But we want provide every application for users with a gui, this script was interest and i woke up thinking that this is and useful missing funciton.

**Comment by LethalEthan** [comment]
Hi just noticed you messaged me back, once I get the GUI and everything else done, you can feel free to implement Bluetooth-Unlock in your OS :smile:

**Pull request merged**
